name: Deploy Frontend to S3

on:
  push:
    branches: [main, master]
    paths:
      - "front/**"
      - ".github/workflows/deploy-front-s3.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: front
        run: npm install

      - name: Run tests
        working-directory: front
        run: npm test

      - name: Build frontend
        working-directory: front
        env:
          # aqu√≠ van TODAS las VITE_ que tu app usa
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VITE_AWS_REGION: ${{ secrets.AWS_REGION }}
          VITE_CLOUDFRONT_URL: ${{ secrets.VITE_CLOUDFRONT_URL }}
          VITE_S3_HLS_PREFIX: ${{ secrets.VITE_S3_HLS_PREFIX }}
          VITE_S3_INPUT_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          VITE_S3_OUTPUT_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload build to S3
        working-directory: front
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync dist s3://$S3_BUCKET_NAME --delete
